#!/bin/bash
wget  http://ftp.unicamp.br/pub/apache/lucene/solr/8.1.1/solr-8.1.1.zip
unzip solr-8.1.1.zip
./solr-8.1.1/bin/install_solr_service.sh solr-8.1.1.zip

service solr stop
service solr start
service solr status
